CREATE TABLE IF NOT EXISTS folders(
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    author_id INT UNSIGNED DEFAULT 0,
    title VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),

    UNIQUE KEY (author_id, title)
);
