version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8888:80"
    networks:
      - default

  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    volumes:
      - "./db_volume:/var/lib/mysql"
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8069:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - default
